[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c3"
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "link-arg=-Tdefmt.x"]

[env]
DEFMT_LOG = "info"

[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
